import Title from "@/components/aui/Title";
import GenerateKey from "./GenerateKey";
import { KeyTable } from "./KeyTable";

export const metadata = {
    title: 'API Keys',
}

export const keys = [
    {
        id: "728ed52f",
        status: "active",
        key: "a1b2c3d4e5f6g7h8i9j0k1l2m3n4o5p6",
    },
    {
        id: "asd3vds2",
        status: "revoked",
        key: "sdf90sdfjnsdjk9i90dsfkdlflnkdsfl",
    },
]

export const columns = [
    {
        accessorKey: "status",
        header: "Status",
    },
    {
        accessorKey: "key",
        header: "Key",
    },
]

// TODO: API Key Generation
// API Keys should be generated by using the user's id which would allow the server
// to know who generated the key for various reasons:
// - Usage Based Billing
// - Who should see what this key is up to
// - Permissions

export default function APIKeysPage({

}) {
    return (
        <>
            <Title
                title={'API Keys'}
                subtitle={'Generate, manage, and revoke API keys from your account.'}
            />
            <KeyTable columns={columns} data={keys} />
            <GenerateKey />
        </>
    )
}