import Title from "@/components/Title";

export const metadata = {
    title: 'API Keys',
}

// TODO: API Key Generation
// API Keys should be generated by using the user's id which would allow the server
// to know who generated the key for various reasons:
// - Usage Based Billing
// - Who should see what this key is up to

export default function APIKeysPage({

}) {
    return (
        <>
            <Title
                title={'API Keys'}
                subtitle={'Generate, manage, and revoke API keys from your account.'}
            />
        </>
    )
}